name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Pull source code
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - uses: docker/setup-buildx-action@v1
      name: Set up Docker Buildx
      id: buildx
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build container image
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          docker.pkg.github.com/${{ github.repository }}/snell:latest
          docker.pkg.github.com/${{ github.repository }}/snell:${{ github.sha }}
